// The first answer in the source bank is correct. The engine shuffles all four.
// Five difficulty pools; each game draws three different questions per pool.
const sources = {
  galapagos: 'https://whc.unesco.org/en/list/1/',
  quito: 'https://whc.unesco.org/en/list/120/',
  cuenca: 'https://whc.unesco.org/en/list/863/',
  sangay: 'https://whc.unesco.org/en/list/260/',
  qhapaq: 'https://whc.unesco.org/en/list/1459/',
  toquilla: 'https://ich.unesco.org/es/RL/tejido-tradicional-del-sombrero-de-paja-toquilla-ecuatoriano-00729',
  pasillo: 'https://ich.unesco.org/es/RL/el-pasillo-canto-y-poesa-01702',
  marimba: 'https://ich.unesco.org/es/RL/01099',
  dollar: 'https://www.bce.fin.ec/25/index.html',
  constitution: 'https://www.asambleanacional.gob.ec/sites/default/files/documents/old/constitucion_de_bolsillo.pdf',
  pichincha: 'https://www.asambleanacional.gob.ec/es/noticia/80139-asamblea-nacional-conmemoro-el-bicentenario-de-la',
  huasipungo: 'https://biblioteca.casadelacultura.gob.ec/bib/19696',
  cumanda: 'https://biblioteca.casadelacultura.gob.ec/bib/25884',
  espejo: 'https://casadelacultura.gob.ec/2025.php/postnoticias/eugenio-de-santa-cruz-y-espejo/',
  perez: 'https://archivo.coe.org.ec/index.php/noticias/3058-hoy-recordamos-la-historica-medalla-de-oro-de-jefferson-perez-en-los-jj-oo-atlanta-1996',
};
const q = (difficulty, id, category, question, answers, explanation, source) => ({ difficulty, id, category, question, answers, explanation, ...(source ? { source: sources[source] || source } : {}) });

export const QUESTIONS = [
  q(1,'ec01','Geografía','¿Cuál es la capital de Ecuador?', ['Quito','Guayaquil','Cuenca','Loja'], 'Quito es la capital del Ecuador y se encuentra en la provincia de Pichincha.'),
  q(1,'ec02','Geografía','¿En qué continente se encuentra Ecuador?', ['América','Europa','Asia','Oceanía'], 'Ecuador se encuentra en América del Sur, junto a Colombia y Perú.'),
  q(1,'ec03','Geografía','¿Qué océano baña las costas ecuatorianas?', ['Pacífico','Atlántico','Índico','Ártico'], 'La costa ecuatoriana está al oeste del país, frente al océano Pacífico.'),
  q(1,'ec04','Vida cotidiana','¿Qué moneda se utiliza en Ecuador desde la dolarización?', ['Dólar estadounidense','Euro','Peso argentino','Real brasileño'], 'La dolarización reemplazó al sucre por el dólar estadounidense en el año 2000.', 'dollar'),
  q(1,'ec05','Símbolos','¿Qué tres colores tiene la bandera de Ecuador?', ['Amarillo, azul y rojo','Verde, blanco y rojo','Azul, blanco y negro','Rojo, blanco y verde'], 'La bandera ecuatoriana tiene tres franjas horizontales: amarilla, azul y roja.'),
  q(1,'ec06','Naturaleza','¿A qué país pertenecen las islas Galápagos?', ['Ecuador','Chile','México','Costa Rica'], 'El archipiélago de Galápagos es parte del territorio ecuatoriano.', 'galapagos'),
  q(1,'ec07','Geografía','¿Qué línea imaginaria da nombre a Ecuador?', ['La línea ecuatorial','El meridiano de Greenwich','El trópico de Cáncer','El círculo polar ártico'], 'La línea ecuatorial divide al planeta en los hemisferios norte y sur y cruza el país.'),
  q(1,'ec08','Geografía','¿Qué cordillera atraviesa la Sierra ecuatoriana?', ['Los Andes','Los Alpes','El Himalaya','Los Pirineos'], 'La cordillera de los Andes recorre el oeste de América del Sur y forma la Sierra ecuatoriana.'),
  q(1,'ec09','Ciudades','¿En qué provincia se encuentra Guayaquil?', ['Guayas','Azuay','Carchi','Napo'], 'Guayaquil es la capital de la provincia del Guayas.'),
  q(1,'ec10','Símbolos','¿Qué color ocupa la franja más ancha de la bandera ecuatoriana?', ['Amarillo','Azul','Rojo','Blanco'], 'La franja amarilla ocupa la mitad de la bandera; la azul y la roja, una cuarta parte cada una.'),
  q(1,'ec11','Producción','¿Cuál de estos productos agrícolas es una exportación emblemática de Ecuador?', ['Banano','Aceituna','Arándano ártico','Trigo sarraceno'], 'El banano es uno de los productos tradicionales de exportación de Ecuador.'),
  q(1,'ec12','Gastronomía','¿Qué ingrediente caracteriza al encebollado ecuatoriano?', ['Pescado','Chocolate','Manzana','Queso azul'], 'El encebollado es una sopa de pescado, habitualmente albacora, con yuca y cebolla.'),
  q(1,'ec13','Ciudades','¿Cuál es la capital de la provincia del Azuay?', ['Cuenca','Ibarra','Ambato','Tulcán'], 'Cuenca es la capital del Azuay, en la Sierra sur del Ecuador.'),
  q(1,'ec14','Naturaleza','¿Qué animal es uno de los símbolos de Galápagos?', ['Tortuga gigante','Oso polar','Canguro','Panda gigante'], 'Las tortugas gigantes son animales emblemáticos del archipiélago.', 'galapagos'),
  q(1,'ec15','Geografía','¿Con qué dos países tiene fronteras terrestres Ecuador?', ['Colombia y Perú','Brasil y Chile','Venezuela y Bolivia','Argentina y Uruguay'], 'Colombia limita con Ecuador al norte y Perú al este y al sur.'),
  q(1,'ec16','Símbolos','¿Qué ave aparece sobre el escudo nacional de Ecuador?', ['Cóndor','Flamenco','Pingüino','Colibrí'], 'El cóndor con las alas extendidas corona el escudo nacional.'),
  q(1,'ec17','Lenguas','Según la Constitución, ¿cuál es el idioma oficial del Ecuador?', ['Castellano','Portugués','Francés','Italiano'], 'El artículo 2 declara oficial al castellano. El kichwa y el shuar también son oficiales de relación intercultural.', 'constitution'),
  q(1,'ec18','Gastronomía','¿Cuál es el ingrediente principal del locro de papa?', ['Papa','Arroz','Lenteja','Yuca'], 'El locro de papa es una sopa andina que suele acompañarse con queso y aguacate.'),

  q(2,'ec19','Geografía','¿Cuál es la montaña más alta de Ecuador sobre el nivel del mar?', ['Chimborazo','Cotopaxi','Pichincha','Tungurahua'], 'El Chimborazo supera los 6.200 metros de altitud y es la cumbre más alta del país.'),
  q(2,'ec20','Ciudades','¿Qué ciudad ecuatoriana es conocida como la Perla del Pacífico?', ['Guayaquil','Latacunga','Riobamba','Tulcán'], 'Guayaquil es conocida tradicionalmente como la Perla del Pacífico.'),
  q(2,'ec21','Ciudades','¿Qué ciudad se llama oficialmente Santa Ana de los Ríos de Cuenca?', ['Cuenca','Loja','Quito','Ibarra'], 'El nombre completo de Cuenca hace referencia a los ríos que atraviesan la ciudad.', 'cuenca'),
  q(2,'ec22','Ciudades','¿Cuál es la capital de Tungurahua?', ['Ambato','Azogues','Puyo','Guaranda'], 'Ambato es la capital de Tungurahua y sede de la Fiesta de la Fruta y de las Flores.'),
  q(2,'ec23','Ciudades','¿Cuál es la capital de Manabí?', ['Portoviejo','Manta','Bahía de Caráquez','Jipijapa'], 'Portoviejo es la capital provincial de Manabí; Manta es otra de sus principales ciudades.'),
  q(2,'ec24','Cultura','¿Con qué provincia ecuatoriana se asocia especialmente la tradición de marimba afroecuatoriana?', ['Esmeraldas','Carchi','Cotopaxi','Azuay'], 'La tradición de marimba de Esmeraldas forma parte del patrimonio cultural inmaterial reconocido por la UNESCO.', 'marimba'),
  q(2,'ec25','Gastronomía','¿Con qué ingrediente se prepara tradicionalmente el bolón de verde?', ['Plátano verde','Papa morada','Arroz integral','Maíz blanco'], 'El plátano verde se cocina y se maja para formar el bolón, con queso o chicharrón.'),
  q(2,'ec26','Gastronomía','¿Durante qué celebración se prepara tradicionalmente la fanesca?', ['Semana Santa','Navidad','Carnaval de Venecia','Año Nuevo chino'], 'La fanesca es una preparación ecuatoriana de Semana Santa, con diversos granos y pescado seco.'),
  q(2,'ec27','Geografía','¿En qué provincia se encuentra Otavalo?', ['Imbabura','Guayas','El Oro','Pastaza'], 'Otavalo pertenece a Imbabura y es reconocido por sus tejidos y su mercado artesanal.'),
  q(2,'ec28','Ciencia','¿Qué naturalista visitó Galápagos y desarrolló la teoría de la evolución por selección natural?', ['Charles Darwin','Isaac Newton','Louis Pasteur','Albert Einstein'], 'Las observaciones de Darwin en Galápagos aportaron a sus ideas sobre la evolución.', 'galapagos'),
  q(2,'ec29','Deportes','¿En qué disciplina se destacó el campeón olímpico Jefferson Pérez?', ['Marcha atlética','Natación','Boxeo','Gimnasia'], 'Jefferson Pérez ganó el oro olímpico en los 20 kilómetros marcha de Atlanta 1996.', 'perez'),
  q(2,'ec30','Producción','¿De qué cultivo se obtiene la materia prima del chocolate?', ['Cacao','Café','Cebada','Quinua'], 'Las semillas de cacao se transforman para producir chocolate; Ecuador es conocido por su cacao fino de aroma.'),
  q(2,'ec31','Gastronomía','¿Qué son los chifles?', ['Láminas fritas de plátano','Una sopa de pescado','Un dulce de leche','Una bebida de maíz'], 'Los chifles son láminas delgadas de plátano fritas, muy comunes en la Costa.'),
  q(2,'ec32','Símbolos','¿Quién escribió la letra del Himno Nacional del Ecuador?', ['Juan León Mera','Jorge Icaza','Pablo Palacio','Juan Montalvo'], 'Juan León Mera escribió la letra de ¡Salve, oh Patria! en 1865.'),
  q(2,'ec33','Símbolos','¿Quién compuso la música del Himno Nacional del Ecuador?', ['Antonio Neumane','Julio Jaramillo','Segundo Cueva Celi','Nicasio Safadi'], 'Antonio Neumane compuso la música del Himno Nacional del Ecuador.'),
  q(2,'ec34','Cultura','¿En qué región tiene una presencia histórica destacada el pueblo montubio?', ['Costa','Región Insular','Antártida','Altiplano boliviano'], 'El pueblo montubio está ligado a comunidades rurales de la Costa ecuatoriana.'),
  q(2,'ec35','Música','¿Cuál de estos es un ritmo tradicional andino del Ecuador?', ['Sanjuanito','Flamenco','Polca irlandesa','Tango finlandés'], 'El sanjuanito es un ritmo y una danza tradicional de los Andes ecuatorianos.'),
  q(2,'ec36','Vida cotidiana','¿Cuál es el prefijo telefónico internacional de Ecuador?', ['+593','+57','+51','+54'], 'El código internacional del Ecuador es +593. Colombia usa +57 y Perú, +51.'),

  q(3,'ec37','Historia','¿En qué año se anunció la dolarización de Ecuador?', ['2000','1985','1990','2010'], 'El anuncio de la dolarización se realizó el 9 de enero de 2000.', 'dollar'),
  q(3,'ec38','Historia','¿Qué fecha conmemora la independencia de Guayaquil de 1820?', ['9 de octubre','24 de mayo','6 de diciembre','12 de febrero'], 'La independencia de Guayaquil se proclamó el 9 de octubre de 1820.'),
  q(3,'ec39','Historia','¿Qué fecha conmemora la independencia de Cuenca de 1820?', ['3 de noviembre','10 de agosto','27 de febrero','25 de julio'], 'Cuenca conmemora su independencia el 3 de noviembre de 1820.'),
  q(3,'ec40','Historia','¿Qué fecha recuerda el Primer Grito de Independencia de Quito de 1809?', ['10 de agosto','9 de octubre','3 de noviembre','6 de diciembre'], 'El 10 de agosto de 1809 se formó en Quito una junta de gobierno.'),
  q(3,'ec41','Historia','¿Quién fue el primer presidente de la República del Ecuador?', ['Juan José Flores','Eloy Alfaro','Vicente Rocafuerte','Gabriel García Moreno'], 'Juan José Flores fue el primer presidente tras la constitución de Ecuador como república en 1830.'),
  q(3,'ec42','Historia','¿Quién comandó el ejército patriota en la Batalla de Pichincha?', ['Antonio José de Sucre','Francisco Pizarro','Sebastián de Benalcázar','Cristóbal Colón'], 'Antonio José de Sucre dirigió las fuerzas patriotas en la batalla del 24 de mayo de 1822.', 'pichincha'),
  q(3,'ec43','Historia','¿De qué Estado formaba parte Ecuador antes de separarse en 1830?', ['Gran Colombia','Virreinato de Nueva España','Imperio del Brasil','Provincias Unidas del Río de la Plata'], 'Los territorios del actual Ecuador integraron la Gran Colombia hasta la separación de 1830.'),
  q(3,'ec44','Literatura','¿Quién escribió la novela Huasipungo?', ['Jorge Icaza','Juan Montalvo','Medardo Ángel Silva','José de la Cuadra'], 'Jorge Icaza publicó Huasipungo en 1934; es una obra emblemática de la narrativa indigenista.', 'huasipungo'),
  q(3,'ec45','Literatura','¿Quién escribió la novela Cumandá?', ['Juan León Mera','Jorge Enrique Adoum','Pablo Palacio','Demetrio Aguilera Malta'], 'Cumandá es una novela de Juan León Mera, publicada originalmente en 1879.', 'cumanda'),
  q(3,'ec46','Arte','¿Qué artista ecuatoriano impulsó la Capilla del Hombre?', ['Oswaldo Guayasamín','Camilo Egas','Eduardo Kingman','Manuel Chili'], 'La Capilla del Hombre, en Quito, fue concebida por el pintor Oswaldo Guayasamín.'),
  q(3,'ec47','Música','¿Qué cantante ecuatoriano fue conocido como el Ruiseñor de América?', ['Julio Jaramillo','Gerardo Morán','Juan Fernando Velasco','Segundo Rosero'], 'Julio Jaramillo, nacido en Guayaquil, fue conocido como el Ruiseñor de América.'),
  q(3,'ec48','Deportes','¿Qué ciclista ecuatoriano ganó el Giro de Italia en 2019?', ['Richard Carapaz','Jefferson Cepeda','Jhonatan Narváez','Byron Guamá'], 'Richard Carapaz ganó la clasificación general del Giro de Italia de 2019.'),
  q(3,'ec49','Deportes','¿Qué club ecuatoriano ganó la Copa Libertadores en 2008?', ['Liga de Quito','Barcelona SC','Emelec','Deportivo Cuenca'], 'Liga Deportiva Universitaria de Quito ganó la final de 2008 frente a Fluminense.'),
  q(3,'ec50','Geografía','¿Cuántas provincias tiene Ecuador?', ['24','18','20','30'], 'Ecuador está dividido en 24 provincias, incluida la provincia insular de Galápagos.'),
  q(3,'ec51','Naturaleza','¿Entre qué provincias se extiende el Parque Nacional Podocarpus?', ['Loja y Zamora Chinchipe','Guayas y Santa Elena','Carchi e Imbabura','Manabí y Esmeraldas'], 'El Parque Nacional Podocarpus se ubica en el sur del país, entre Loja y Zamora Chinchipe.'),
  q(3,'ec52','Geografía','¿En qué provincia está la laguna del Quilotoa?', ['Cotopaxi','Carchi','Bolívar','Morona Santiago'], 'Quilotoa es una laguna ubicada en un cráter volcánico de la provincia de Cotopaxi.'),
  q(3,'ec53','Cultura','¿Con qué fenómeno astronómico se relaciona el Inti Raymi andino de junio?', ['Solsticio de junio','Eclipse lunar anual','Perihelio de enero','Lluvia de meteoros de diciembre'], 'El Inti Raymi es una celebración andina del Sol vinculada al solsticio de junio y al ciclo agrícola.'),
  q(3,'ec54','Patrimonio','¿En qué provincia se encuentra el complejo arqueológico de Ingapirca?', ['Cañar','Azuay','Pichincha','Los Ríos'], 'Ingapirca se encuentra en la provincia del Cañar y conserva vestigios cañaris e incas.'),

  q(4,'ec55','Patrimonio','¿En qué año fue inscrita Quito en la Lista del Patrimonio Mundial de la UNESCO?', ['1978','1986','1999','2008'], 'Quito ingresó en la Lista del Patrimonio Mundial en 1978.', 'quito'),
  q(4,'ec56','Patrimonio','¿En qué año se inscribió el centro histórico de Cuenca en la Lista del Patrimonio Mundial?', ['1999','1978','1983','2014'], 'El centro histórico de Santa Ana de los Ríos de Cuenca fue inscrito en 1999.', 'cuenca'),
  q(4,'ec57','Patrimonio','¿En qué año reconoció la UNESCO el tejido tradicional del sombrero ecuatoriano de paja toquilla?', ['2012','1992','2001','2021'], 'El tejido tradicional del sombrero ecuatoriano de paja toquilla fue inscrito como patrimonio cultural inmaterial en 2012.', 'toquilla'),
  q(4,'ec58','Música','¿En qué año fue inscrito el pasillo ecuatoriano como patrimonio cultural inmaterial de la UNESCO?', ['2021','2008','2012','2015'], 'La UNESCO inscribió El Pasillo, canto y poesía en su lista representativa en 2021.', 'pasillo'),
  q(4,'ec59','Música','¿En qué año se inscribió la tradición de marimba de Esmeraldas y del Pacífico Sur colombiano en la UNESCO?', ['2015','1999','2012','2023'], 'La inscripción conjunta de la música, cantos y bailes tradicionales se realizó en 2015.', 'marimba'),
  q(4,'ec60','Ciencia','¿En qué año visitó Charles Darwin las islas Galápagos?', ['1835','1809','1859','1901'], 'Darwin visitó Galápagos en 1835, durante el viaje del HMS Beagle.', 'galapagos'),
  q(4,'ec61','Deportes','¿En qué edición de los Juegos Olímpicos ganó Jefferson Pérez el primer oro ecuatoriano?', ['Atlanta 1996','Barcelona 1992','Sídney 2000','Atenas 2004'], 'Jefferson Pérez ganó los 20 kilómetros marcha en Atlanta 1996.', 'perez'),
  q(4,'ec62','Deportes','¿En qué edición olímpica ganó Richard Carapaz el oro en ciclismo de ruta?', ['Tokio 2020','Río 2016','Londres 2012','Pekín 2008'], 'Ganó en Tokio 2020. Esa edición conservó su nombre, aunque se celebró en 2021.'),
  q(4,'ec63','Geografía','¿Cuál es la isla de mayor superficie en Galápagos?', ['Isabela','Santa Cruz','San Cristóbal','Floreana'], 'Isabela es la isla más extensa del archipiélago de Galápagos.'),
  q(4,'ec64','Naturaleza','¿En qué provincia está el Parque Nacional Cajas?', ['Azuay','Tungurahua','Napo','Santa Elena'], 'El Parque Nacional Cajas se encuentra al oeste de Cuenca, en Azuay.'),
  q(4,'ec65','Ciudades','¿Cuál es la capital de la provincia de El Oro?', ['Machala','Zaruma','Santa Rosa','Huaquillas'], 'Machala es la capital provincial de El Oro y se conoce como la Capital Bananera del Mundo.'),
  q(4,'ec66','Literatura','¿Quién escribió Siete tratados?', ['Juan Montalvo','Jorge Icaza','Juan León Mera','Pablo Palacio'], 'Siete tratados es una colección de ensayos del escritor ambateño Juan Montalvo.'),
  q(4,'ec67','Literatura','¿Quién es el autor de la novela Baldomera?', ['Alfredo Pareja Diezcanseco','Jorge Enrique Adoum','José de la Cuadra','Juan León Mera'], 'Alfredo Pareja Diezcanseco publicó Baldomera en 1938.'),
  q(4,'ec68','Literatura','¿Quién escribió Los Sangurimas?', ['José de la Cuadra','Pablo Palacio','Juan Montalvo','Jorge Icaza'], 'Los Sangurimas es una obra de José de la Cuadra, publicada en 1934.'),
  q(4,'ec69','Poesía','¿Quién escribió el poema El alma en los labios?', ['Medardo Ángel Silva','Jorge Carrera Andrade','César Dávila Andrade','José Joaquín de Olmedo'], 'El poema es de Medardo Ángel Silva, uno de los autores de la llamada Generación Decapitada.'),
  q(4,'ec70','Historia','¿En qué ciudad se reunió la Asamblea Constituyente que elaboró la Constitución de 2008?', ['Montecristi','Riobamba','Guayaquil','Loja'], 'La Asamblea Constituyente sesionó en Montecristi, en la provincia de Manabí.', 'constitution'),
  q(4,'ec71','Historia','¿Qué ciudad fue sede de la primera Asamblea Constituyente del Ecuador en 1830?', ['Riobamba','Cuenca','Portoviejo','Ibarra'], 'La primera Asamblea Constituyente se reunió en Riobamba y elaboró la Constitución de 1830.'),
  q(4,'ec72','Patrimonio','¿Qué nombre artístico tuvo el escultor quiteño Manuel Chili?', ['Caspicara','Guayasamín','Kingman','Miguel de Santiago'], 'Manuel Chili, conocido como Caspicara, fue un destacado escultor de la Escuela Quiteña.'),

  q(5,'ec73','Historia','¿En qué fecha exacta se libró la Batalla de Pichincha?', ['24 de mayo de 1822','10 de agosto de 1809','9 de octubre de 1820','3 de noviembre de 1820'], 'La victoria patriota del 24 de mayo de 1822 permitió la liberación de Quito.', 'pichincha'),
  q(5,'ec74','Historia','¿Qué fecha se conmemora como la fundación española de Quito?', ['6 de diciembre de 1534','12 de octubre de 1492','24 de mayo de 1822','10 de agosto de 1809'], 'La fundación española de San Francisco de Quito se conmemora el 6 de diciembre de 1534.'),
  q(5,'ec75','Economía','¿Cuál fue la tasa de conversión fijada al dolarizar el Ecuador?', ['25.000 sucres por dólar','10.000 sucres por dólar','1.000 sucres por dólar','50.000 sucres por dólar'], 'La tasa de conversión se fijó en 25.000 sucres por dólar estadounidense.'),
  q(5,'ec76','Ciencia','¿Cómo se llamaba el barco en el que Darwin viajó a Galápagos?', ['HMS Beagle','HMS Endeavour','La Santa María','HMS Victory'], 'Darwin visitó Galápagos a bordo del HMS Beagle en 1835.'),
  q(5,'ec77','Arqueología','¿Qué dos culturas dejaron una huella especialmente importante en Ingapirca?', ['Cañari e inca','Maya y azteca','Moche y nazca','Taína y olmeca'], 'Ingapirca conserva la historia de la población cañari y de la posterior presencia inca.'),
  q(5,'ec78','Arqueología','¿A qué cultura ecuatoriana se asocian las pequeñas figurillas conocidas como Venus?', ['Valdivia','Inca','Caranqui','Puruhá'], 'Las Venus de Valdivia son figurillas de una antigua cultura de la costa ecuatoriana.'),
  q(5,'ec79','Arqueología','¿Qué cultura prehispánica ecuatoriana es célebre por sus botellas silbato?', ['Chorrera','Caranqui','Inca','Cañari'], 'La cerámica Chorrera incluye botellas silbato de gran refinamiento técnico.'),
  q(5,'ec80','Geología','¿Sobre qué placa tectónica se encuentra el archipiélago de Galápagos?', ['Nazca','Euroasiática','Norteamericana','Arábiga'], 'Galápagos se sitúa sobre la placa de Nazca, junto a un punto caliente volcánico.'),
  q(5,'ec81','Constitución','¿Qué artículo de la Constitución ecuatoriana empieza reconociendo derechos a la naturaleza o Pacha Mama?', ['Artículo 71','Artículo 1','Artículo 24','Artículo 95'], 'El artículo 71 reconoce el derecho de la naturaleza al respeto de su existencia y sus ciclos vitales.', 'constitution'),
  q(5,'ec82','Patrimonio','¿En qué año fue inscrito el Parque Nacional Sangay como Patrimonio Mundial?', ['1983','1978','1999','2012'], 'El Parque Nacional Sangay fue inscrito en la Lista del Patrimonio Mundial en 1983.', 'sangay'),
  q(5,'ec83','Patrimonio','¿Cuántos países comparten el sitio del Patrimonio Mundial Qhapaq Ñan, Sistema Vial Andino?', ['Seis','Tres','Cuatro','Ocho'], 'Lo comparten Argentina, Bolivia, Chile, Colombia, Ecuador y Perú.', 'qhapaq'),
  q(5,'ec84','Patrimonio','¿En qué año se inscribieron las islas Galápagos en la Lista del Patrimonio Mundial?', ['1978','1983','1999','2014'], 'Galápagos fue inscrito en 1978, en la primera lista de sitios del Patrimonio Mundial.', 'galapagos'),
  q(5,'ec85','Naturaleza','¿Qué reptil endémico de Galápagos se alimenta de algas en el mar?', ['Iguana marina','Caimán negro','Boa esmeralda','Lagarto cornudo'], 'La iguana marina de Galápagos se adapta al medio marino para alimentarse de algas.', 'galapagos'),
  q(5,'ec86','Geografía','¿Cuál de estos NO es uno de los cuatro ríos principales de Cuenca?', ['Guayas','Tomebamba','Yanuncay','Tarqui'], 'Los cuatro ríos principales de Cuenca son Tomebamba, Yanuncay, Tarqui y Machángara.'),
  q(5,'ec87','Patrimonio','¿Con qué cantón de Chimborazo se asocia el tramo ferroviario de la Nariz del Diablo?', ['Alausí','Guano','Chambo','Colta'], 'La Nariz del Diablo es un tramo emblemático del ferrocarril asociado al cantón Alausí.'),
  q(5,'ec88','Historia','¿Quién escribió Historia del Reino de Quito?', ['Juan de Velasco','Eugenio Espejo','Pedro Vicente Maldonado','Juan José Flores'], 'El jesuita Juan de Velasco escribió Historia del Reino de Quito en el siglo XVIII.'),
  q(5,'ec89','Historia','¿Qué ecuatoriana ejerció el voto en 1924, convirtiéndose en una pionera del sufragio femenino?', ['Matilde Hidalgo','Manuela Sáenz','Dolores Cacuango','Tránsito Amaguaña'], 'Matilde Hidalgo de Procel ejerció el voto en 1924 y abrió camino a los derechos políticos de las mujeres.'),
  q(5,'ec90','Historia','¿Quién dirigió el periódico Primicias de la Cultura de Quito, publicado en 1792?', ['Eugenio Espejo','Juan León Mera','José de la Cuadra','Vicente Rocafuerte'], 'Eugenio Espejo impulsó Primicias de la Cultura de Quito, una publicación clave de la Ilustración quiteña.', 'espejo'),
];
